# Generated by Django 6.0.1 on 2026-01-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_course_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='university1', to='university.university'),
        ),
    ]
