# Generated by Django 6.0.1 on 2026-01-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_course_university'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='universitycourse',
            name='unique university, course, name, semester and duration_weeks',
        ),
        migrations.RenameField(
            model_name='universitycourse',
            old_name='course',
            new_name='courses',
        ),
        migrations.RemoveField(
            model_name='course',
            name='university',
        ),
        migrations.AddConstraint(
            model_name='universitycourse',
            constraint=models.UniqueConstraint(fields=('university', 'courses', 'semester', 'duration_weeks'), name='unique university, courses, name, semester and duration_weeks'),
        ),
    ]
