# Generated by Django 6.0.1 on 2026-01-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_remove_universitycourse_unique_university_course_name_semester_and_duration_weeks_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='universitycourse',
            name='unique university, courses, name, semester and duration_weeks',
        ),
        migrations.RenameField(
            model_name='universitycourse',
            old_name='courses',
            new_name='course',
        ),
        migrations.AddConstraint(
            model_name='universitycourse',
            constraint=models.UniqueConstraint(fields=('university', 'course', 'semester', 'duration_weeks'), name='unique university, course, name, semester and duration_weeks'),
        ),
    ]
